name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
      - '.github/workflows/deploy-demo.yml'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo
          publish_branch: gh-pages
          commit_message: 'Deploy demo to GitHub Pages'
